apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-ex-git
    app.kubernetes.io/component: nodejs-ex-git
    app.kubernetes.io/instance: nodejs-ex-git
    app.kubernetes.io/name: nodejs-ex-git
    app.kubernetes.io/part-of: nodejs-ex-git-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
  name: nodejs-ex-git
  namespace: db-gitops
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodejs-ex-git
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodejs-ex-git
        deploymentconfig: nodejs-ex-git
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/db/nodejs-ex-git@sha256:725e58fe4018d34af1da8b2aa7749166e4f481ad2613d8b71f9a9b66af4d7bb2
        imagePullPolicy: Always
        name: nodejs-ex-git
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
